[features]
seeds = false
skip-lint = false

[programs.devnet]
solmint = "GvGUNhrtzUUwhP9PCgF24m7KWtvU4zQCFyjDpvtyRAaP"

[programs.mainnet]
solmint = "GvGUNhrtzUUwhP9PCgF24m7KWtvU4zQCFyjDpvtyRAaP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/ilpr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solmint.json app/src/idl/solmint.json"
